x-base-image:
  versions:
    moc: &moc 0.7.6 
    mops: &mops 1.2.0
  name: &base_name "local/cycleops-v1"

services:
  base:
    build:
      context: .
      dockerfile: Dockerfile.base
      args:
        MOC_VERSION: *moc
        MOPS_VERSION: *mops
    image: *base_name
  wasm:
    build:
      context: .
      args:
        IMAGE: *base_name
    volumes:
      - ./out:/project/out
    environment:
      compress : no
    command: bash --login build.sh
